# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=256)),
            ],
            options={
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='MirrorSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='mirrorlog',
            name='mirror_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pypi_frontend.MirrorSite'),
        ),
    ]
