# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangopypi2.apps.pypi_packages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pypi_metadata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('allow_version_overwrite', models.BooleanField(default=False)),
                ('upload_directory', models.CharField(default=b'dists', help_text=b'Direcory relative to MEDIA_ROOT in which user uploads are kept', max_length=256)),
            ],
            options={
                'ordering': ('-timestamp',),
                'get_latest_by': 'timestamp',
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to=djangopypi2.apps.pypi_packages.models.distribution_upload_path)),
                ('md5_digest', models.CharField(blank=True, editable=False, max_length=32)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('signature', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('filetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='pypi_metadata.DistributionType')),
                ('platform', models.ForeignKey(help_text=b'Platform name or None if platform agnostic', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='pypi_metadata.PlatformName')),
                ('pyversion', models.ForeignKey(help_text=b'Python version, or None for any version of Python', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='pypi_metadata.PythonVersion')),
            ],
            options={
                'verbose_name': 'distribution',
                'verbose_name_plural': 'distributions',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('name', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('auto_hide', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('maintainers', models.ManyToManyField(blank=True, related_name='packages_maintained', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(blank=True, related_name='packages_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'get_latest_by': 'releases__latest',
                'verbose_name': 'package',
                'verbose_name_plural': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(editable=False, max_length=128)),
                ('metadata_version', models.CharField(default=b'1.0', max_length=64)),
                ('package_info', djangopypi2.apps.pypi_packages.models.PackageInfoField(editable=False)),
                ('hidden', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='pypi_packages.Package')),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'verbose_name': 'release',
                'verbose_name_plural': 'releases',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pypi_packages.Release')),
            ],
            options={
                'verbose_name': 'release review',
                'verbose_name_plural': 'release reviews',
            },
        ),
        migrations.AddField(
            model_name='distribution',
            name='release',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='pypi_packages.Release'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='uploader',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributions_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set([('package', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together=set([('release', 'filetype', 'pyversion', 'platform')]),
        ),
    ]
